CREATE TABLE noteful_notes (
    noteid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    modified TIMESTAMPTZ DEFAULT now(),
    folderid INTEGER REFERENCES
        noteful_folders(id) ON DELETE CASCADE NOT NULL,
    content TEXT
);